### ISSUE TITLE
Suggestion: Add an option to not clear Jewel type

### ISSUE THREAD

**Issue by syntheer** [Hannah-GBS/VH-Jewel-Calc#15] opened 2023-03-20 13:09 UTC
It would be nice to have a quick ability to create many Jewels of the same time, eg. Mining Speed Jewels, that only vary with Size/Speed.
Currently pressing the Add Jewel clears the form, so one has to select the type again.

**Comment by Hannah-GBS** [comment] 2023-03-22 12:28
Duplicate of #12

**Closed as not planned by Hannah-GBS** 2023-03-22 12:28 UTC
